const express = require('express')
const app = express()
const PORT = 3000

const weapons = {
    'glock18': {
        'weaponType': 'Pistol',
        'price': '$200',
        'magSize': '12',
        'team': 'T side',
        'Description': 'Deadly up close, just a nuisance at range',
        'Consider': 'Consider in the first round of half',
        'difficulty': '2/4',
    },
    'dual berettas ': {
        'weaponType': 'Pistol',
        'price': '$300',
        'magSize': '30',
        'team': 'CT/T side',
        'Description': 'Two rapid-fire pistols for the price of one',
        'Consider': 'Consider in the first round of half',
        'difficulty': '2/4',
    },'p250': {
        'weaponType': 'Pistol',
        'price': '$300',
        'magSize': '12',
        'team': 'CT/T side',
        'Description': 'A populat, if modest, damage upgrade',
        'Consider': 'Consider in eco rounds',
        'difficulty': '1/4',
    },'tec9': {
        'weaponType': 'Pistol',
        'price': '$500',
        'magSize': '15',
        'team': 'T side',
        'Description': 'Highly mobile, effective at range and upclose',
        'Consider': 'Consider in eco rounds',
        'difficulty': '3/4',
    },'desert eagle': {
        'weaponType': 'Pistol',
        'price': '$700',
        'magSize': '7',
        'team': 'CT/T side',
        'Description': 'A lethal headshot at any range',
        'Consider': 'Consider in eco rounds',
        'difficulty': '4/4',
    },'usps': {
        'weaponType': 'Pistol',
        'price': '$200',
        'magSize': '10',
        'team': 'CT side',
        'Description': 'Precise, silent, and (somewhat) deadly',
        'Consider': 'Consider in the first round of half',
        'difficulty': '2/4',
    },'p2000': {
        'weaponType': 'Pistol',
        'price': '$200',
        'magSize': '10',
        'team': 'CT side',
        'Description': 'Accurate at range, spammable up close',
        'Consider': 'Consider in the first round of the half',
        'difficulty': '2/4',
    },'cz75 auto': {
        'weaponType': 'Pistol',
        'price': '$500',
        'magSize': '12',
        'team': 'CT/T side',
        'Description': 'A burst of firepower to steal enemy weapons',
        'Consider': 'Consider in eco rounds',
        'difficulty': '4/4',
    },'five seven': {
        'weaponType': 'Pistol',
        'price': '$500',
        'magSize': '15',
        'team': 'CT side',
        'Description': 'Power, speed, and precision for a price',
        'Consider': 'Consider in eco rounds',
        'difficulty': '2/4',
    },
    'r8 revolver': {
        'weaponType': 'Pistol',
        'price': '$600',
        'magSize': '8',
        'team': 'CT/T side',
        'Description': 'Deals massive damage after a short delay',
        'Consider': 'Consider in eco rounds',
        'difficulty': '4/4',
    },
    'nova': {
        'weaponType': 'Mid-tier/ Shotgun',
        'price': '$1050',
        'magSize': '8',
        'team': 'CT/T side',
        'Description': 'Versatile shotgun for close quater combat',
        'Consider': 'Consider in force buy rounds',
        'difficulty': '2/4',
    },
    'xm1014': {
        'weaponType': 'Mid-tier/ Shotgun',
        'price': '$2000',
        'magSize': '8',
        'team': 'CT/T side',
        'Description': 'A full-auto rapid-fire monster',
        'Consider': 'Consider in force buy rounds',
        'difficulty': '1/4',
    },
    'sawed off': {
        'weaponType': 'Mid-tier/ Shotgun',
        'price': '$1100',
        'magSize': '8',
        'team': 'T side',
        'Description': 'High powered shotgun for close engagemants',
        'Consider': 'Consider in force buy rounds',
        'difficulty': '2/4',
    },
    'mag7': {
        'weaponType': 'Mid-tier/ Shotgun',
        'price': '$1300',
        'magSize': '7',
        'team': 'CT side',
        'Description': 'Take the enemy by surprise, reload, repeat!',
        'Consider': 'Consider in force buy rounds',
        'difficulty': '2/4',
    },
    'mp9': {
        'weaponType': 'Mid-teir/ SMG',
        'price': '$1250',
        'magSize': '',
        'team': 'CT side',
        'Description': 'A burst of damage to deny an enemy rush',
        'Consider': 'Consider in the first three rounds of the half',
        'difficulty': '1/4',
    },
    'mac 10': {
        'weaponType': 'Mid-tier/ SMG',
        'price': '$1050',
        'magSize': '25',
        'team': 'T side',
        'Description': 'A run and gun tool for breaching bombsites',
        'Consider': 'Consider in first three rounds of half',
        'difficulty': '1/4',
    },
    'p90': {
        'weaponType': 'Mid-tier/ SMG',
        'price': '$2350',
        'magSize': '30',
        'team': 'CT/T side',
        'Description': 'An endless bullet hose bested only by rifles',
        'Consider': 'Consider in full buy rounds',
        'difficulty': '1/4',
    },
    'mp5': {
        'weaponType': 'Mid-tier/ SMG',
        'price': '$1500',
        'magSize': '25',
        'team': 'CT/T side',
        'Description': 'Nimble and stealthy for mid-range damage',
        'Consider': 'Consider in force buy rounds',
        'difficulty': '2/4',
    },
    'pp bizon': {
        'weaponType': 'Mid-tier/ SMG',
        'price': '$1400',
        'magSize': '45',
        'team': 'CT/T side',
        'Description': 'A hail of bullets to mow down unarmored enemies',
        'Consider': 'Consider in the first three rounds of half',
        'difficulty': '2/4',
    },
    'mp7': {
        'weaponType': 'Mid-tier/ SMG',
        'price': '$1500',
        'magSize': '30',
        'team': 'CT/T side',
        'Description': 'Easy to control for reliable mid-range damage',
        'Consider': 'Consider in force buy rounds',
        'difficulty': '2/4',
    },
    'ump': {
        'weaponType': 'Mid-tier/ SMG',
        'price': '$1200',
        'magSize': '',
        'team': 'CT/T side',
        'Description': 'Good armor penetration for mid-range fights',
        'Consider': 'Consider in force buy rounds',
        'difficulty': '3/4',
    },
    'nagev': {
        'weaponType': 'Mid-tier/ LMG',
        'price': '$1700',
        'magSize': '150',
        'team': 'CT/T side',
        'Description': 'Pin-point suppressive fire to buy some time',
        'Consider': 'Consider in force buy rounds',
        'difficulty': '4/4',
    },
    'm249': {
        'weaponType': 'Mid-tier/ LMG',
        'price': '$5200',
        'magSize': '100',
        'team': 'CT/T side',
        'Description': 'At least you wont have to reload...',
        'Consider': 'Consider only under special circumstances',
        'difficulty': '3/4',
    },
    'ak47': {
        'weaponType': 'Rifle',
        'price': '$2700',
        'magSize': '30',
        'team': 'T side',
        'Description': 'The classic, accurate, and deadly workhorse',
        'Consider': 'Consider in full buy rounds',
        'difficulty': '4/4',
    },
    'm4a1s': {
        'weaponType': 'Rifle',
        'price': '$2900',
        'magSize': '20',
        'team': 'CT side',
        'Description': 'Precise, silent, tracer-free',
        'Consider': 'Consider in full buy rounds',
        'difficulty': '3/4',
    },
    'm4a4': {
        'weaponType': 'Rifle',
        'price': '$3100',
        'magSize': '30',
        'team': 'CT side',
        'Description': 'Good accuracy, with ammo to spare',
        'Consider': 'Consider in full buy rounds',
        'difficulty': '3/4',
    },
    'famas': {
        'weaponType': 'Rifle',
        'price': '$2050',
        'magSize': '25',
        'team': 'CT side',
        'Description': 'Cheap but effective against armored enemies',
        'Consider': 'Consider in force buy rounds',
        'difficulty': '3/4',
    },
    'galil': {
        'weaponType': 'Rifle',
        'price': '$1800',
        'magSize': '35',
        'team': 'T side',
        'Description': 'Cheap but effective against armored enemies',
        'Consider': 'Consider in force buy rounds',
        'difficulty': '3/4',
    },
    'sg': {
        'weaponType': 'Rifle',
        'price': '$3000',
        'magSize': '35',
        'team': 'T side',
        'Description': 'A lethal weapon made deadlier with a scope',
        'Consider': 'Consider in full buy rounds',
        'difficulty': '3/4',
    },
    'aug': {
        'weaponType': 'Rifle',
        'price': '$3300',
        'magSize': '30',
        'team': 'CT side',
        'Description': 'An optional scope for exceptional accuracy',
        'Consider': 'Consider in full buy rounds',
        'difficulty': '3/4',
    },
    'awp': {
        'weaponType': 'Rifle/ Sniper',
        'price': '$4750',
        'magSize': '5',
        'team': 'CT/T side',
        'Description': 'Devastating power for the confident sniper',
        'Consider': 'Consider in full buy rounds',
        'difficulty': '3/4',
    },
    'ssg': {
        'weaponType': 'Rifle/ Sniper',
        'price': '$1700',
        'magSize': '10',
        'team': 'CT/T side',
        'Description': 'Light and powerful long-distance damage dealer',
        'Consider': 'Consider in force buy rounds',
        'difficulty': '4/4',
    },
    'scar': {
        'weaponType': 'Rifle/ Auto sniper',
        'price': '$5000',
        'magSize': '10',
        'team': 'CT side',
        'Description': 'A potent (if risky) tool to hold a position',
        'Consider': 'Consider only under special circumstances',
        'difficulty': '3/4',
    },
    'g3sg1': {
        'weaponType': 'Rifle/ Auto sniper',
        'price': '$5000',
        'magSize': '15',
        'team': 'T side',
        'Description': 'High risk/reward automatic sniper rifle',
        'Consider': 'Consider only under special circumstances',
        'difficulty': '3/4',
    },
    'zues': {
        'weaponType': '',
        'price': '$200',
        'magSize': '1',
        'team': 'CT/T side',
        'Description': 'A single-bbbbbbuse one shot kill at short range',
        'Consider': 'Use at your own risk',
        'difficulty': '4/4',
    },
    'flashbang': {
        'weaponType': 'Grenade',
        'price': '$200',
        'team': 'CT/T side',
        'Description': 'Blinds/deafens nearby players',
        'Consider': 'Throw prior to attack',
        'difficulty': '4/4',
    },
    'smoke': {
        'weaponType': 'Grenade',
        'price': '$300',
        'team': 'CT/T side',
        'Description': 'Creates large smoke cloud',
        'Consider': 'Throw to cut off enemy lines of site',
        'difficulty': '3/4',
    },
    'he grenade': {
        'weaponType': 'Grenade',
        'price': '$300',
        'team': 'CT/ T side',
        'Description': 'Deal damage or clear smoke grenades',
        'Consider': 'Use with discretion',
        'difficulty': '3/4',
    },
    'incendairy grenade': {
        'weaponType': 'Grenade',
        'price': '$600',
        'team': 'CT side',
        'Description': 'Stifles enemy attack with fire',
        'Consider': 'Throw at the first sign of trouble',
        'difficulty': '3/4',
    },
    'molotov': {
        'weaponType': 'Grenade',
        'price': '$400',
        'team': 'T side',
        'Description': 'Clears out hiding spots with fire',
        'Consider': 'Throw before attacking bombsite',
        'difficulty': '3/4',
    },
    'decoy': {
        'weaponType': 'Granade',
        'price': '$50',
        'team': 'CT/T side',
        'Description': 'Mimics a weapon firing sound',
        'Consider': 'Throw early to confuse the enemy',
        'difficulty': '3/4',
    },
    'kevlar vest': {
        'weaponType': 'Armor',
        'price': '$600',
        'team': 'CT/T side',
        'Description': 'Protects everything but your head',
        'Consider': 'Consider in the first round of the half',
        'difficulty': '1/4',
    },
    'kevlar + helmet': {
        'weaponType': 'Armor',
        'price': '$1000',
        'team': 'CT/T side',
        'Description': 'Survive all but the most lethal bullets',
        'Consider': 'Consider in full buy and force buy rounds',
        'difficulty': '1/4',
    },
    'defuse kit': {
        'weaponType': 'Kit',
        'price': '$400',
        'team': 'CT side',
        'Description': 'Cut your defuse time in half',
        'Consider': 'Dont be a loser, buy a defuser!',
        'difficulty': '1/4',
    },
    'unknown': {
        'weaponType': 'Unknown',
        'price': 'Unknown',
        'magSize': 'Unknown',
        'team': 'Unknown',
        'Description': 'Unknown',
        'Consider': 'Unknown',
        'difficulty': 'Unknown',
    }
}

app.get('/', (req, res) => {
    res.sendFile(__dirname + '/index.html')
})

app.get('/api/:name',(req,res) => {
    const weaponName = req.params.name.toLowerCase()
    if(weapons[weaponName]){
        res.json(weapons[weaponName])
    }else{
        res.json(weapons['unknown'])
    }
    
})

app.listen(PORT, () => {
    console.log(`The server is now running on port ${PORT}! You better go catch it!`)
})